name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # TODO: this is an extension-commands plugin.
      - name: Test asdf alias
        run: true
      # There's no tool-version to test.
      # - name: asdf_plugin_test
      #   uses: asdf-vm/actions/plugin-test@v1.0.0
      #   with:
      #     command: asdf help | grep 'asdf alias'
      #   env:
      #     GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
