name: Lint
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  shellcheck:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: shellcheck
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get packages
        uses: delgurth/get-package@v5
        with:
          snap: shfmt
          brew: shellcheck shfmt
          apt-get: shellcheck
      - name: Run ShellCheck
        run: |
          shellcheck -V
          shellcheck lib/commands/*.bash -P lib/
          if command -v shfmt &> /dev/null
          then
            shfmt -d -i 2 -ci .
          else
            echo "shfmt failed to install, only seems to happen with https://github.com/nektos/act"
          fi
